name: Deploy to AWS

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SPACE_TRACK_USERNAME: ${{ secrets.SPACE_TRACK_USERNAME }}
      SPACE_TRACK_PASSWORD: ${{ secrets.SPACE_TRACK_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Serverless deploy to production environment
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run deploy-prod
      - name: Serverless deploy to development environment
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: npm run deploy-dev
